Fixed upstream component versions
openshift/origin-aggregated-logging pull request #2170
Opened 2021-08-26 09:10 UTC by vimalk78

### Description
Fixed upstream component versions to
 - elasticsearch: 6.8.1
 - kibana: 6.8.1
 - fluentd: 1.7.4

/cc @igor-karpukhin @periklis 
/assign @jcantrill 

### Links

- JIRA: https://issues.redhat.com/browse/LOG-1700

2021-09-02 13:04 UTC, periklis commented
/retest

2021-09-03 17:52 UTC, vimalk78 commented on elasticsearch/Dockerfile
> +        version=v6.8.1
this label is used by OSBS to version the image

2021-09-03 17:58 UTC, vimalk78 commented on elasticsearch/Dockerfile
> +ENV BUILD_VERSION=6.8.1
after some research i found that this variable is used to add OCP version in the Docker build.
so perhaps this variable can be deleted

2021-09-04 05:01 UTC, vimalk78 commented
/retest

2021-09-04 06:43 UTC, vimalk78 commented
/retest

2021-09-06 04:22 UTC, periklis requested changes
Missing the changes in curator image.

2021-09-08 09:10 UTC, periklis approved these changes
/lgtm

2021-09-08 11:44 UTC, periklis commented
/retest

2021-09-08 17:23 UTC, jcantrill reviewed
/approve

2021-09-08 17:24 UTC, jcantrill commented
/retest

2021-09-08 20:17 UTC, merged